### ISSUE TITLE
Fit TabNetRegressor on weighted samples

### ISSUE THREAD

**Issue by parsiad** [dreamquark-ai/tabnet#266]
## Feature request

**What is the expected behavior?**

Fit TabNetRegressor on a set of `(x_i, y_i)` samples with corresponding weights `w_i`.

**What is motivation or use case for adding/changing the behavior?**

Many regression applications use non-uniformly weighted samples. LightGBM and XGBoost both support this feature.

**How should this be implemented in your opinion?**

Suggested API:

```
clf = TabNetRegressor()
clf.fit(
  X_train, y_train, w_train=w_train,
  eval_set=[(X_valid, y_valid, w_valid)]
)
```

**Are you willing to work on this yourself?**

Yes, though I would like to discuss with maintainers first.

**Comment by Optimox** [comment]
Hi,

This is available, you can put a numpy array of weights in the fit function and it will do what you are asking.

It might not be obvious in the README though.

**Comment by parsiad** [comment]
Thank you for the quick reply. It's unclear to me from the docs how to do
this; I don't see any options for specifying per sample weights (I do see
the option for specifying per class weights, though). Can I trouble you for
an example?

**Comment by Optimox** [comment]
It’s the same parameters, which accepts bool, dict or numpy arrays. The docstrings must be up to date, even though the README is not.

**Comment by parsiad** [comment]
Thank you for your reply.

I'm confused though: how do you specify training and eval weights if it is
just one parameter? Does it only accept training weights? I would be very
appreciative of a code snippet if you happen to have one.

**Comment by Optimox** [comment]
The weights are for training only, they impact the sampling weights, not the loss function.

If weights are outputs/labels driven then the best way is to directly change the loss function or the evaluation metric, which will allow you to monitor your scores on any set of data.

If weights are input driven (example penalize more younglings/elderly people) then it’s going to be harder because you do not have access to inputs when computing loss/metrics.

About the code snippet, I’m on my phone right now so it’s not ideal. If y_train.shape is (N,1) then your weights should be a positive array of shape (N,1) corresponding to y_train/X_train for the importance weight of every sample.

**Comment by parsiad** [comment]
I tried your suggestion, but it fails with an error (see below). If I remove `weights`, it works.

```python
w_train = np.ones_like(y_train) / y_train.size
regressor.fit(
    x_train,
    y_train,
    eval_set=[(x_validate, y_validate)],
    eval_metric=['rmse'],
    loss_fn=torch.nn.MSELoss(),
    max_epochs=200,
    weights=w_train,
)
regressor.save_model(name)
```

```
Device used : cuda
Traceback (most recent call last):
  File "housing.py", line 43, in <module>
    regressor.fit(
  File "/home/parsiad/env/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 223, in fit
    self._train_epoch(train_dataloader)
  File "/home/parsiad/env/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 434, in _train_epoch
    batch_logs = self._train_batch(X, y)
  File "/home/parsiad/env/lib/python3.8/site-packages/pytorch_tabnet/abstract_model.py", line 469, in _train_batch
    output, M_loss = self.network(X)
  File "/home/parsiad/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/parsiad/env/lib/python3.8/site-packages/pytorch_tabnet/tab_network.py", line 583, in forward
    return self.tabnet(x)
  File "/home/parsiad/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/parsiad/env/lib/python3.8/site-packages/pytorch_tabnet/tab_network.py", line 468, in forward
    steps_output, M_loss = self.encoder(x)
  File "/home/parsiad/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/parsiad/env/lib/python3.8/site-packages/pytorch_tabnet/tab_network.py", line 150, in forward
    x = self.initial_bn(x)
  File "/home/parsiad/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/parsiad/env/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 131, in forward
    return F.batch_norm(
  File "/home/parsiad/env/lib/python3.8/site-packages/torch/nn/functional.py", line 2056, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 12259 elements not 8
```

**Comment by parsiad** [comment]
Update: it seems like `weights` **expects a vector** so doing `weights=np.ones([y_train.size]) / y_train.size` instead works. Thanks!
